set(VENDOR_JSON_HEADER nlohmann/json.hpp)
set(VENDOR_SPARSEPP_HEADERS
  spp_stdint.h
  spp_timer.h
  spp.h
  spp_memory.h
  spp_smartptr.h
  spp_config.h
  spp_utils.h
  spp_dlalloc.h
  spp_traits.h
  )
set(VENDOR_SPDLOG_HEADERS
  details/async_logger_impl.h
  details/async_log_helper.h
  details/file_helper.h
  details/logger_impl.h
  details/log_msg.h
  details/mpmc_bounded_q.h
  details/null_mutex.h
  details/os.h
  details/pattern_formatter_impl.h
  details/registry.h
  details/spdlog_impl.h
  fmt/bundled/format.cc
  fmt/bundled/format.h
  fmt/bundled/LICENSE.rst
  fmt/bundled/ostream.cc
  fmt/bundled/ostream.h
  fmt/bundled/posix.cc
  fmt/bundled/posix.h
  fmt/bundled/printf.cc
  fmt/bundled/printf.h
  fmt/bundled/time.h
  sinks/android_sink.h
  sinks/ansicolor_sink.h
  sinks/base_sink.h
  sinks/dist_sink.h
  sinks/file_sinks.h
  sinks/msvc_sink.h
  sinks/null_sink.h
  sinks/ostream_sink.h
  sinks/sink.h
  sinks/stdout_sinks.h
  sinks/syslog_sink.h
  sinks/wincolor_sink.h
  sinks/windebug_sink.h
  fmt/fmt.h
  fmt/ostr.h
  async_logger.h
  common.h
  formatter.h
  logger.h
  spdlog.h
  tweakme.h
  )
